dist: trusty
language: java
jdk:
  - oraclejdk15
branches:
  only:
    - master
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
    - CODECOV_TOKEN="7107ca4b-77ea-4f90-b04e-ecaab2598d0e"
    - DISPLAY=:99
before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- $DISPLAY -ac -screen 0 1280x1024x24"
  - sleep 3
before_install: sudo apt-get install xvfb
install: mvn install -DskipTests=true -Dgpg.skip=true
script: ./build.sh
addons:
  apt:
    packages:
      - xvfb