dist: bionic
language: java
jdk:
  - oraclejdk15
services:
  - postgresql
branches:
  only:
    - master
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
    - CODECOV_TOKEN="7107ca4b-77ea-4f90-b04e-ecaab2598d0e"
    - DISPLAY=:99
before_script:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- $DISPLAY -ac -screen 0 1280x1024x24"
  - sleep 3
before_install:
  - psql -c 'create database deutsch_trainer;' -U postgres
  - psql deutsch_trainer -U postgres -d deutsch_trainer -f ./database/db.sql
  - sudo apt-get install xvfb
install: mvn install -DskipTests=true -Dgpg.skip=true -Ddt.db.user=postgres
script: ./build.sh
addons:
  apt:
    packages:
      - xvfb