dist: trusty
language: java
jdk:
  - oraclejdk15
branches:
  only:
    - master
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
    - CODECOV_TOKEN="7107ca4b-77ea-4f90-b04e-ecaab2598d0e"
    - DISPLAY=0.0
script: ./build.sh