version: 1.0.{build}
skip_tags: true
branches:
  only:
    - master
image: Ubuntu2004
services:
  - postgresql
environment:
  PGUSER: postgres
  PGPASSWORD: Password12!
build_script:
  - echo $PWD $USER $PGUSER $PGPASSWORD
  - sudo psql -U postgres -c 'create database my_test_db;'
