version: "{build}"

image: Ubuntu

skip_tags: true
branches:
  only:
    - master

install:
  - npm install jest --global
  - npm install json-server --global
  - npm install

test_script:
  - node --version
  - npm --version
  - json-server --watch data/db.json --port 8080 & jest --passWithNoTests
