version: 1.0.{build}
skip_tags: true
branches:
  only:
    - master
image: Ubuntu2004
services:
  - postgresql
environment:
  PGUSER: postgres
  PGPASSWORD: Password12!
  CODECOV_TOKEN: 7107ca4b-77ea-4f90-b04e-ecaab2598d0e"
  DISPLAY: :99
  matrix:
    - JAVA_HOME: /usr/lib/jvm/java-15-openjdk-amd64
build_script:
  - echo $JAVA_HOME
  - echo $PWD $USER $PGUSER $PGPASSWORD
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- $DISPLAY -ac -screen 0 1280x1024x24
  - sleep 3
  - psql -c 'create database deutsch_trainer;'
  - psql deutsch_trainer -d deutsch_trainer -f ./database/db.sql
  - sudo apt-get install xvfb
  - mvn clean install package -Ddt.db.user=postgres
  - bash <(curl -s https://codecov.io/bash)