version: "{build}"

image: Ubuntu

skip_tags: true
branches:
  only:
    - master

install:
  - npm install jest --global
  - npm install

test_script:
  - node --version
  - npm --version
  - jest --passWithNoTests
