/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.maven.example;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.codegen.maven.example.tables.DtUser;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DT_USER_ID_UINDEX = Internal.createIndex(DSL.name("dt_user_id_uindex"), DtUser.DT_USER, new OrderField[] { DtUser.DT_USER.ID }, true);
    public static final Index DT_USER_USERNAME_UINDEX = Internal.createIndex(DSL.name("dt_user_username_uindex"), DtUser.DT_USER, new OrderField[] { DtUser.DT_USER.USERNAME }, true);
}
