/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.maven.example;


import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;
import org.jooq.Table;
import org.jooq.UDT;
import org.jooq.codegen.maven.example.tables.DtUser;
import org.jooq.codegen.maven.example.tables.GeographyColumns;
import org.jooq.codegen.maven.example.tables.GeometryColumns;
import org.jooq.codegen.maven.example.tables.SpatialRefSys;
import org.jooq.codegen.maven.example.tables.StDump;
import org.jooq.codegen.maven.example.tables.StDumppoints;
import org.jooq.codegen.maven.example.tables.StDumprings;
import org.jooq.codegen.maven.example.tables.StSubdivide;
import org.jooq.codegen.maven.example.tables.records.StDumpRecord;
import org.jooq.codegen.maven.example.tables.records.StDumppointsRecord;
import org.jooq.codegen.maven.example.tables.records.StDumpringsRecord;
import org.jooq.codegen.maven.example.tables.records.StSubdivideRecord;
import org.jooq.codegen.maven.example.udt.GeometryDump;
import org.jooq.codegen.maven.example.udt.ValidDetail;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.dt_user</code>.
     */
    public final DtUser DT_USER = DtUser.DT_USER;

    /**
     * The table <code>public.geography_columns</code>.
     */
    public final GeographyColumns GEOGRAPHY_COLUMNS = GeographyColumns.GEOGRAPHY_COLUMNS;

    /**
     * The table <code>public.geometry_columns</code>.
     */
    public final GeometryColumns GEOMETRY_COLUMNS = GeometryColumns.GEOMETRY_COLUMNS;

    /**
     * The table <code>public.spatial_ref_sys</code>.
     */
    public final SpatialRefSys SPATIAL_REF_SYS = SpatialRefSys.SPATIAL_REF_SYS;

    /**
     * The table <code>public.st_dump</code>.
     */
    public final StDump ST_DUMP = StDump.ST_DUMP;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StDumpRecord> ST_DUMP(
          Configuration configuration
        , Object __1
    ) {
        return configuration.dsl().selectFrom(StDump.ST_DUMP.call(
              __1
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDump ST_DUMP(
          Object __1
    ) {
        return StDump.ST_DUMP.call(
            __1
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDump ST_DUMP(
          Field<Object> __1
    ) {
        return StDump.ST_DUMP.call(
            __1
        );
    }

    /**
     * The table <code>public.st_dumppoints</code>.
     */
    public final StDumppoints ST_DUMPPOINTS = StDumppoints.ST_DUMPPOINTS;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StDumppointsRecord> ST_DUMPPOINTS(
          Configuration configuration
        , Object __1
    ) {
        return configuration.dsl().selectFrom(StDumppoints.ST_DUMPPOINTS.call(
              __1
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDumppoints ST_DUMPPOINTS(
          Object __1
    ) {
        return StDumppoints.ST_DUMPPOINTS.call(
            __1
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDumppoints ST_DUMPPOINTS(
          Field<Object> __1
    ) {
        return StDumppoints.ST_DUMPPOINTS.call(
            __1
        );
    }

    /**
     * The table <code>public.st_dumprings</code>.
     */
    public final StDumprings ST_DUMPRINGS = StDumprings.ST_DUMPRINGS;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StDumpringsRecord> ST_DUMPRINGS(
          Configuration configuration
        , Object __1
    ) {
        return configuration.dsl().selectFrom(StDumprings.ST_DUMPRINGS.call(
              __1
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDumprings ST_DUMPRINGS(
          Object __1
    ) {
        return StDumprings.ST_DUMPRINGS.call(
            __1
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDumprings ST_DUMPRINGS(
          Field<Object> __1
    ) {
        return StDumprings.ST_DUMPRINGS.call(
            __1
        );
    }

    /**
     * The table <code>public.st_subdivide</code>.
     */
    public final StSubdivide ST_SUBDIVIDE = StSubdivide.ST_SUBDIVIDE;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StSubdivideRecord> ST_SUBDIVIDE(
          Configuration configuration
        , Object geom
        , Integer maxvertices
    ) {
        return configuration.dsl().selectFrom(StSubdivide.ST_SUBDIVIDE.call(
              geom
            , maxvertices
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StSubdivide ST_SUBDIVIDE(
          Object geom
        , Integer maxvertices
    ) {
        return StSubdivide.ST_SUBDIVIDE.call(
            geom,
            maxvertices
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StSubdivide ST_SUBDIVIDE(
          Field<Object> geom
        , Field<Integer> maxvertices
    ) {
        return StSubdivide.ST_SUBDIVIDE.call(
            geom,
            maxvertices
        );
    }

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            DtUser.DT_USER,
            GeographyColumns.GEOGRAPHY_COLUMNS,
            GeometryColumns.GEOMETRY_COLUMNS,
            SpatialRefSys.SPATIAL_REF_SYS,
            StDump.ST_DUMP,
            StDumppoints.ST_DUMPPOINTS,
            StDumprings.ST_DUMPRINGS,
            StSubdivide.ST_SUBDIVIDE
        );
    }

    @Override
    public final List<UDT<?>> getUDTs() {
        return Arrays.asList(
            GeometryDump.GEOMETRY_DUMP,
            ValidDetail.VALID_DETAIL
        );
    }
}
