/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.maven.example;


import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;
import org.jooq.codegen.maven.example.tables.DtUser;
import org.jooq.codegen.maven.example.tables.GeographyColumns;
import org.jooq.codegen.maven.example.tables.GeometryColumns;
import org.jooq.codegen.maven.example.tables.SpatialRefSys;
import org.jooq.codegen.maven.example.tables.StDump;
import org.jooq.codegen.maven.example.tables.StDumppoints;
import org.jooq.codegen.maven.example.tables.StDumprings;
import org.jooq.codegen.maven.example.tables.StSubdivide;
import org.jooq.codegen.maven.example.tables.records.StDumpRecord;
import org.jooq.codegen.maven.example.tables.records.StDumppointsRecord;
import org.jooq.codegen.maven.example.tables.records.StDumpringsRecord;
import org.jooq.codegen.maven.example.tables.records.StSubdivideRecord;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.dt_user</code>.
     */
    public static final DtUser DT_USER = DtUser.DT_USER;

    /**
     * The table <code>public.geography_columns</code>.
     */
    public static final GeographyColumns GEOGRAPHY_COLUMNS = GeographyColumns.GEOGRAPHY_COLUMNS;

    /**
     * The table <code>public.geometry_columns</code>.
     */
    public static final GeometryColumns GEOMETRY_COLUMNS = GeometryColumns.GEOMETRY_COLUMNS;

    /**
     * The table <code>public.spatial_ref_sys</code>.
     */
    public static final SpatialRefSys SPATIAL_REF_SYS = SpatialRefSys.SPATIAL_REF_SYS;

    /**
     * The table <code>public.st_dump</code>.
     */
    public static final StDump ST_DUMP = StDump.ST_DUMP;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StDumpRecord> ST_DUMP(
          Configuration configuration
        , Object __1
    ) {
        return configuration.dsl().selectFrom(StDump.ST_DUMP.call(
              __1
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDump ST_DUMP(
          Object __1
    ) {
        return StDump.ST_DUMP.call(
            __1
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDump ST_DUMP(
          Field<Object> __1
    ) {
        return StDump.ST_DUMP.call(
            __1
        );
    }

    /**
     * The table <code>public.st_dumppoints</code>.
     */
    public static final StDumppoints ST_DUMPPOINTS = StDumppoints.ST_DUMPPOINTS;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StDumppointsRecord> ST_DUMPPOINTS(
          Configuration configuration
        , Object __1
    ) {
        return configuration.dsl().selectFrom(StDumppoints.ST_DUMPPOINTS.call(
              __1
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDumppoints ST_DUMPPOINTS(
          Object __1
    ) {
        return StDumppoints.ST_DUMPPOINTS.call(
            __1
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDumppoints ST_DUMPPOINTS(
          Field<Object> __1
    ) {
        return StDumppoints.ST_DUMPPOINTS.call(
            __1
        );
    }

    /**
     * The table <code>public.st_dumprings</code>.
     */
    public static final StDumprings ST_DUMPRINGS = StDumprings.ST_DUMPRINGS;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StDumpringsRecord> ST_DUMPRINGS(
          Configuration configuration
        , Object __1
    ) {
        return configuration.dsl().selectFrom(StDumprings.ST_DUMPRINGS.call(
              __1
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDumprings ST_DUMPRINGS(
          Object __1
    ) {
        return StDumprings.ST_DUMPRINGS.call(
            __1
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StDumprings ST_DUMPRINGS(
          Field<Object> __1
    ) {
        return StDumprings.ST_DUMPRINGS.call(
            __1
        );
    }

    /**
     * The table <code>public.st_subdivide</code>.
     */
    public static final StSubdivide ST_SUBDIVIDE = StSubdivide.ST_SUBDIVIDE;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static Result<StSubdivideRecord> ST_SUBDIVIDE(
          Configuration configuration
        , Object geom
        , Integer maxvertices
    ) {
        return configuration.dsl().selectFrom(StSubdivide.ST_SUBDIVIDE.call(
              geom
            , maxvertices
        )).fetch();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StSubdivide ST_SUBDIVIDE(
          Object geom
        , Integer maxvertices
    ) {
        return StSubdivide.ST_SUBDIVIDE.call(
            geom,
            maxvertices
        );
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static StSubdivide ST_SUBDIVIDE(
          Field<Object> geom
        , Field<Integer> maxvertices
    ) {
        return StSubdivide.ST_SUBDIVIDE.call(
            geom,
            maxvertices
        );
    }
}
