/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.maven.example;


import org.jooq.codegen.maven.example.udt.GeometryDump;
import org.jooq.codegen.maven.example.udt.ValidDetail;


/**
 * Convenience access to all UDTs in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UDTs {

    /**
     * The type <code>public.geometry_dump</code>
     */
    public static final GeometryDump GEOMETRY_DUMP = GeometryDump.GEOMETRY_DUMP;

    /**
     * The type <code>public.valid_detail</code>
     */
    public static final ValidDetail VALID_DETAIL = ValidDetail.VALID_DETAIL;
}
