/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.maven.example.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.codegen.maven.example.Public;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StAsgml2 extends AbstractRoutine<String> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.st_asgml.RETURN_VALUE</code>.
     */
    public static final Parameter<String> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.st_asgml.version</code>.
     */
    public static final Parameter<Integer> VERSION = Internal.createParameter("version", SQLDataType.INTEGER, false, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static final Parameter<Object> GEOM = Internal.createParameter("geom", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * The parameter <code>public.st_asgml.maxdecimaldigits</code>.
     */
    public static final Parameter<Integer> MAXDECIMALDIGITS = Internal.createParameter("maxdecimaldigits", SQLDataType.INTEGER.defaultValue(DSL.field("15", SQLDataType.INTEGER)), true, false);

    /**
     * The parameter <code>public.st_asgml.options</code>.
     */
    public static final Parameter<Integer> OPTIONS = Internal.createParameter("options", SQLDataType.INTEGER.defaultValue(DSL.field("0", SQLDataType.INTEGER)), true, false);

    /**
     * The parameter <code>public.st_asgml.nprefix</code>.
     */
    public static final Parameter<String> NPREFIX = Internal.createParameter("nprefix", SQLDataType.CLOB.defaultValue(DSL.field("NULL::text", SQLDataType.CLOB)), true, false);

    /**
     * The parameter <code>public.st_asgml.id</code>.
     */
    public static final Parameter<String> ID = Internal.createParameter("id", SQLDataType.CLOB.defaultValue(DSL.field("NULL::text", SQLDataType.CLOB)), true, false);

    /**
     * Create a new routine call instance
     */
    public StAsgml2() {
        super("st_asgml", Public.PUBLIC, SQLDataType.CLOB);

        setReturnParameter(RETURN_VALUE);
        addInParameter(VERSION);
        addInParameter(GEOM);
        addInParameter(MAXDECIMALDIGITS);
        addInParameter(OPTIONS);
        addInParameter(NPREFIX);
        addInParameter(ID);
        setOverloaded(true);
    }

    /**
     * Set the <code>version</code> parameter IN value to the routine
     */
    public void setVersion(Integer value) {
        setValue(VERSION, value);
    }

    /**
     * Set the <code>version</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setVersion(Field<Integer> field) {
        setField(VERSION, field);
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    public void setGeom(Object value) {
        setValue(GEOM, value);
    }

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setGeom(Field<Object> field) {
        setField(GEOM, field);
    }

    /**
     * Set the <code>maxdecimaldigits</code> parameter IN value to the routine
     */
    public void setMaxdecimaldigits(Integer value) {
        setValue(MAXDECIMALDIGITS, value);
    }

    /**
     * Set the <code>maxdecimaldigits</code> parameter to the function to be
     * used with a {@link org.jooq.Select} statement
     */
    public void setMaxdecimaldigits(Field<Integer> field) {
        setField(MAXDECIMALDIGITS, field);
    }

    /**
     * Set the <code>options</code> parameter IN value to the routine
     */
    public void setOptions(Integer value) {
        setValue(OPTIONS, value);
    }

    /**
     * Set the <code>options</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setOptions(Field<Integer> field) {
        setField(OPTIONS, field);
    }

    /**
     * Set the <code>nprefix</code> parameter IN value to the routine
     */
    public void setNprefix(String value) {
        setValue(NPREFIX, value);
    }

    /**
     * Set the <code>nprefix</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setNprefix(Field<String> field) {
        setField(NPREFIX, field);
    }

    /**
     * Set the <code>id</code> parameter IN value to the routine
     */
    public void setId(String value) {
        setValue(ID, value);
    }

    /**
     * Set the <code>id</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setId(Field<String> field) {
        setField(ID, field);
    }
}
