/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.maven.example.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.codegen.maven.example.Public;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * @deprecated Unknown data type. Please define an explicit {@link
 * org.jooq.Binding} to specify how this type should be handled. Deprecation can
 * be turned off using {@literal <deprecationOnUnknownTypes/>} in your code
 * generator configuration.
 */
@Deprecated
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StBuffer1 extends AbstractRoutine<Object> {

    private static final long serialVersionUID = 1L;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static final Parameter<Object> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static final Parameter<Object> GEOM = Internal.createParameter("geom", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * The parameter <code>public.st_buffer.radius</code>.
     */
    public static final Parameter<Double> RADIUS = Internal.createParameter("radius", SQLDataType.DOUBLE, false, false);

    /**
     * The parameter <code>public.st_buffer.options</code>.
     */
    public static final Parameter<String> OPTIONS = Internal.createParameter("options", SQLDataType.CLOB.defaultValue(DSL.field("''::text", SQLDataType.CLOB)), true, false);

    /**
     * Create a new routine call instance
     */
    public StBuffer1() {
        super("st_buffer", Public.PUBLIC, org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""));

        setReturnParameter(RETURN_VALUE);
        addInParameter(GEOM);
        addInParameter(RADIUS);
        addInParameter(OPTIONS);
        setOverloaded(true);
    }

    /**
     * Set the <code>geom</code> parameter IN value to the routine
     */
    public void setGeom(Object value) {
        setValue(GEOM, value);
    }

    /**
     * Set the <code>geom</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setGeom(Field<Object> field) {
        setField(GEOM, field);
    }

    /**
     * Set the <code>radius</code> parameter IN value to the routine
     */
    public void setRadius(Double value) {
        setValue(RADIUS, value);
    }

    /**
     * Set the <code>radius</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setRadius(Field<Double> field) {
        setField(RADIUS, field);
    }

    /**
     * Set the <code>options</code> parameter IN value to the routine
     */
    public void setOptions(String value) {
        setValue(OPTIONS, value);
    }

    /**
     * Set the <code>options</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setOptions(Field<String> field) {
        setField(OPTIONS, field);
    }
}
