/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.maven.example.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.codegen.maven.example.Public;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StInterpolatepoint extends AbstractRoutine<Double> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.st_interpolatepoint.RETURN_VALUE</code>.
     */
    public static final Parameter<Double> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.DOUBLE, false, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static final Parameter<Object> LINE = Internal.createParameter("line", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static final Parameter<Object> POINT = Internal.createParameter("point", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * Create a new routine call instance
     */
    public StInterpolatepoint() {
        super("st_interpolatepoint", Public.PUBLIC, SQLDataType.DOUBLE);

        setReturnParameter(RETURN_VALUE);
        addInParameter(LINE);
        addInParameter(POINT);
    }

    /**
     * Set the <code>line</code> parameter IN value to the routine
     */
    public void setLine(Object value) {
        setValue(LINE, value);
    }

    /**
     * Set the <code>line</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setLine(Field<Object> field) {
        setField(LINE, field);
    }

    /**
     * Set the <code>point</code> parameter IN value to the routine
     */
    public void setPoint(Object value) {
        setValue(POINT, value);
    }

    /**
     * Set the <code>point</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setPoint(Field<Object> field) {
        setField(POINT, field);
    }
}
