/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.maven.example.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.codegen.maven.example.Public;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * @deprecated Unknown data type. Please define an explicit {@link
 * org.jooq.Binding} to specify how this type should be handled. Deprecation can
 * be turned off using {@literal <deprecationOnUnknownTypes/>} in your code
 * generator configuration.
 */
@Deprecated
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StLinefromencodedpolyline extends AbstractRoutine<Object> {

    private static final long serialVersionUID = 1L;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static final Parameter<Object> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * The parameter <code>public.st_linefromencodedpolyline.txtin</code>.
     */
    public static final Parameter<String> TXTIN = Internal.createParameter("txtin", SQLDataType.CLOB, false, false);

    /**
     * The parameter <code>public.st_linefromencodedpolyline.nprecision</code>.
     */
    public static final Parameter<Integer> NPRECISION = Internal.createParameter("nprecision", SQLDataType.INTEGER.defaultValue(DSL.field("5", SQLDataType.INTEGER)), true, false);

    /**
     * Create a new routine call instance
     */
    public StLinefromencodedpolyline() {
        super("st_linefromencodedpolyline", Public.PUBLIC, org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""));

        setReturnParameter(RETURN_VALUE);
        addInParameter(TXTIN);
        addInParameter(NPRECISION);
    }

    /**
     * Set the <code>txtin</code> parameter IN value to the routine
     */
    public void setTxtin(String value) {
        setValue(TXTIN, value);
    }

    /**
     * Set the <code>txtin</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setTxtin(Field<String> field) {
        setField(TXTIN, field);
    }

    /**
     * Set the <code>nprecision</code> parameter IN value to the routine
     */
    public void setNprecision(Integer value) {
        setValue(NPRECISION, value);
    }

    /**
     * Set the <code>nprecision</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    public void setNprecision(Field<Integer> field) {
        setField(NPRECISION, field);
    }
}
