/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.maven.example.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.codegen.maven.example.Public;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * @deprecated Unknown data type. Please define an explicit {@link
 * org.jooq.Binding} to specify how this type should be handled. Deprecation can
 * be turned off using {@literal <deprecationOnUnknownTypes/>} in your code
 * generator configuration.
 */
@Deprecated
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StLocatebetween extends AbstractRoutine<Object> {

    private static final long serialVersionUID = 1L;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static final Parameter<Object> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static final Parameter<Object> GEOMETRY = Internal.createParameter("geometry", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * The parameter <code>public.st_locatebetween.frommeasure</code>.
     */
    public static final Parameter<Double> FROMMEASURE = Internal.createParameter("frommeasure", SQLDataType.DOUBLE, false, false);

    /**
     * The parameter <code>public.st_locatebetween.tomeasure</code>.
     */
    public static final Parameter<Double> TOMEASURE = Internal.createParameter("tomeasure", SQLDataType.DOUBLE, false, false);

    /**
     * The parameter <code>public.st_locatebetween.leftrightoffset</code>.
     */
    public static final Parameter<Double> LEFTRIGHTOFFSET = Internal.createParameter("leftrightoffset", SQLDataType.DOUBLE.defaultValue(DSL.field("0.0", SQLDataType.DOUBLE)), true, false);

    /**
     * Create a new routine call instance
     */
    public StLocatebetween() {
        super("st_locatebetween", Public.PUBLIC, org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""));

        setReturnParameter(RETURN_VALUE);
        addInParameter(GEOMETRY);
        addInParameter(FROMMEASURE);
        addInParameter(TOMEASURE);
        addInParameter(LEFTRIGHTOFFSET);
    }

    /**
     * Set the <code>geometry</code> parameter IN value to the routine
     */
    public void setGeometry(Object value) {
        setValue(GEOMETRY, value);
    }

    /**
     * Set the <code>geometry</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setGeometry(Field<Object> field) {
        setField(GEOMETRY, field);
    }

    /**
     * Set the <code>frommeasure</code> parameter IN value to the routine
     */
    public void setFrommeasure(Double value) {
        setValue(FROMMEASURE, value);
    }

    /**
     * Set the <code>frommeasure</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    public void setFrommeasure(Field<Double> field) {
        setField(FROMMEASURE, field);
    }

    /**
     * Set the <code>tomeasure</code> parameter IN value to the routine
     */
    public void setTomeasure(Double value) {
        setValue(TOMEASURE, value);
    }

    /**
     * Set the <code>tomeasure</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    public void setTomeasure(Field<Double> field) {
        setField(TOMEASURE, field);
    }

    /**
     * Set the <code>leftrightoffset</code> parameter IN value to the routine
     */
    public void setLeftrightoffset(Double value) {
        setValue(LEFTRIGHTOFFSET, value);
    }

    /**
     * Set the <code>leftrightoffset</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    public void setLeftrightoffset(Field<Double> field) {
        setField(LEFTRIGHTOFFSET, field);
    }
}
