/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.maven.example.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.codegen.maven.example.Public;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * @deprecated Unknown data type. Please define an explicit {@link
 * org.jooq.Binding} to specify how this type should be handled. Deprecation can
 * be turned off using {@literal <deprecationOnUnknownTypes/>} in your code
 * generator configuration.
 */
@Deprecated
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StLocatebetweenelevations extends AbstractRoutine<Object> {

    private static final long serialVersionUID = 1L;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static final Parameter<Object> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public static final Parameter<Object> GEOMETRY = Internal.createParameter("geometry", org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""), false, false);

    /**
     * The parameter
     * <code>public.st_locatebetweenelevations.fromelevation</code>.
     */
    public static final Parameter<Double> FROMELEVATION = Internal.createParameter("fromelevation", SQLDataType.DOUBLE, false, false);

    /**
     * The parameter <code>public.st_locatebetweenelevations.toelevation</code>.
     */
    public static final Parameter<Double> TOELEVATION = Internal.createParameter("toelevation", SQLDataType.DOUBLE, false, false);

    /**
     * Create a new routine call instance
     */
    public StLocatebetweenelevations() {
        super("st_locatebetweenelevations", Public.PUBLIC, org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\""));

        setReturnParameter(RETURN_VALUE);
        addInParameter(GEOMETRY);
        addInParameter(FROMELEVATION);
        addInParameter(TOELEVATION);
    }

    /**
     * Set the <code>geometry</code> parameter IN value to the routine
     */
    public void setGeometry(Object value) {
        setValue(GEOMETRY, value);
    }

    /**
     * Set the <code>geometry</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setGeometry(Field<Object> field) {
        setField(GEOMETRY, field);
    }

    /**
     * Set the <code>fromelevation</code> parameter IN value to the routine
     */
    public void setFromelevation(Double value) {
        setValue(FROMELEVATION, value);
    }

    /**
     * Set the <code>fromelevation</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    public void setFromelevation(Field<Double> field) {
        setField(FROMELEVATION, field);
    }

    /**
     * Set the <code>toelevation</code> parameter IN value to the routine
     */
    public void setToelevation(Double value) {
        setValue(TOELEVATION, value);
    }

    /**
     * Set the <code>toelevation</code> parameter to the function to be used
     * with a {@link org.jooq.Select} statement
     */
    public void setToelevation(Field<Double> field) {
        setField(TOELEVATION, field);
    }
}
