/*
 * This file is generated by jOOQ.
 */
package org.jooq.codegen.maven.example.tables;


import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.codegen.maven.example.Public;
import org.jooq.codegen.maven.example.tables.records.StSubdivideRecord;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StSubdivide extends TableImpl<StSubdivideRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.st_subdivide</code>
     */
    public static final StSubdivide ST_SUBDIVIDE = new StSubdivide();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StSubdivideRecord> getRecordType() {
        return StSubdivideRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link
     * org.jooq.Binding} to specify how this type should be handled. Deprecation
     * can be turned off using {@literal <deprecationOnUnknownTypes/>} in your
     * code generator configuration.
     */
    @Deprecated
    public final TableField<StSubdivideRecord, Object> ST_SUBDIVIDE_ = createField(DSL.name("st_subdivide"), org.jooq.impl.DefaultDataType.getDefaultDataType("\"geometry\""), this, "");

    private StSubdivide(Name alias, Table<StSubdivideRecord> aliased) {
        this(alias, aliased, new Field[] {
            DSL.val(null, org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\"")),
            DSL.val(null, SQLDataType.INTEGER.defaultValue(DSL.field("256", SQLDataType.INTEGER)))
        });
    }

    private StSubdivide(Name alias, Table<StSubdivideRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function());
    }

    /**
     * Create an aliased <code>public.st_subdivide</code> table reference
     */
    public StSubdivide(String alias) {
        this(DSL.name(alias), ST_SUBDIVIDE);
    }

    /**
     * Create an aliased <code>public.st_subdivide</code> table reference
     */
    public StSubdivide(Name alias) {
        this(alias, ST_SUBDIVIDE);
    }

    /**
     * Create a <code>public.st_subdivide</code> table reference
     */
    public StSubdivide() {
        this(DSL.name("st_subdivide"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public StSubdivide as(String alias) {
        return new StSubdivide(DSL.name(alias), this, parameters);
    }

    @Override
    public StSubdivide as(Name alias) {
        return new StSubdivide(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public StSubdivide rename(String name) {
        return new StSubdivide(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public StSubdivide rename(Name name) {
        return new StSubdivide(name, null, parameters);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row1<Object> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * Call this table-valued function
     */
    public StSubdivide call(
          Object geom
        , Integer maxvertices
    ) {
        StSubdivide result = new StSubdivide(DSL.name("st_subdivide"), null, new Field[] {
            DSL.val(geom, org.jooq.impl.DefaultDataType.getDefaultDataType("\"public\".\"geometry\"")),
            DSL.val(maxvertices, SQLDataType.INTEGER.defaultValue(DSL.field("256", SQLDataType.INTEGER)))
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }

    /**
     * Call this table-valued function
     */
    public StSubdivide call(
          Field<Object> geom
        , Field<Integer> maxvertices
    ) {
        StSubdivide result = new StSubdivide(DSL.name("st_subdivide"), null, new Field[] {
            geom,
            maxvertices
        });

        return aliased() ? result.as(getUnqualifiedName()) : result;
    }
}
